image_root: '/home/minwoo/Distillation_Project/datasets/vision/coco/images/'
ann_root: '/home/minwoo/Distillation_Project/datasets/vision/coco/annotations/'
coco_gt_root: '/home/minwoo/Distillation_Project/datasets/vision/coco/annotation/coco_gt'
pretrained: '/home/minwoo/Distillation_Project/output/official_pretrain_checkpoint/model_base_14M.pth'
output_dir: 'output/caption_zeroshot/base'
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
my_bert_size: 'base'
image_size: 224
batch_size: 32
init_lr: 1.0e-5
weight_decay: 0.05
min_lr: 0
max_epoch: 1
prompt: ''
use_spice: false
max_length: 20
min_length: 5
num_beams: 3
