train_file: ['/home/minwoo/Distillation_Project/datasets/vision/coco/annotations/coco_karpathy_train.json'
            #  '/export/share/junnan-li/VL_pretrain/annotation/vg_caption.json',
             ]
laion_path: ''   

# size of vit model; base or large
vit: 'base' 
vit_grad_ckpt: False
vit_ckpt_layer: 0

# size of language model: base, medium, minilm 중 하나로 설정

image_size: 224
# batch_size: 75 # 변경해야함
batch_size: 16 # 4.68배 작음

queue_size: 57600
alpha: 0.4

# optimizer
weight_decay: 0.05
# init_lr: 3e-4
init_lr: 1e-4 # 3배 줄임
min_lr: 1e-6
warmup_lr: 1e-6
lr_decay_rate: 0.9
max_epoch: 3 # 변경
# warmup_steps: 3000 
warmup_steps: 6000 # 2배 늘림



