train_file: ['/home/minwoo/Distillation_Project/datasets/vision/coco/annotations/coco_karpathy_train.json',
             '/home/minwoo/Distillation_Project/datasets/vision/vg/annotation/vg_train.json'
             ]
laion_path: ''   
image_root_coco: '/home/minwoo/Distillation_Project/datasets/vision/coco/images/'
image_root_vg: '/home/minwoo/Distillation_Project/datasets/vision/vg/images/'

######## cc12m을 제거하고 트레인을 돌려본다. vit small로 가보자 ##### 
# cc12m_tar_path: '/home/minwoo/Distillation_Project/datasets/vision/cc12m/cc12m_dataset'
# cc12m_tar_path: '/data4/minwoo/cc12m/cc12m_dataset'
cc12m_tar_path: ''
cc12m_ratio: 5

## 데이터셋 명시하기 - 변경필수 혹은 이후에 딕셔너리로?
used_dataset: 'coco_vg'
# used_dataset: 'coco_only' # 테스트를 위해

# output_dir: '/home/minwoo/Distillation_Project/output/pretrain_coco_cc12m_small'
# output_dir: '/home/minwoo/Distillation_Project/output/pretrain_coco_only_baseline'
output_dir: '/home/minwoo/Distillation_Project/output/pretrain_coco_vg_baseline'

# new) tenserboard log interval
tb_train_log_interval: 50
tb_val_log_interval: 1000

# size of vit model; base or large

vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0

# vit: 'small_reg' # small로 달아봄. 스몰은 작동을 안하더라
# vit_grad_ckpt: False
# vit_ckpt_layer: 0

# size of language model: base, medium, minilm 중 하나로 설정
# my_bert_size: 'minilm'
my_bert_size: 'base'


## 벨리데이션 과정
#### 수정부분 시작: COCO Karpathy validation loss ####
val_loss_enabled: true

val_loss_file: '/home/minwoo/Distillation_Project/datasets/vision/coco/annotations/coco_karpathy_val.json'
val_loss_image_root: '/home/minwoo/Distillation_Project/datasets/vision/coco/images/'

val_loss_batch_size: 32
val_loss_num_workers: 4
val_loss_caption_mode: first
val_loss_drop_last: true
val_loss_pin_memory: true

val_loss_print_freq: 50

# 처음에는 중간 validation 끄기
val_loss_interval_steps: 500
val_loss_max_batches: 30 # 전체가 39더라

# epoch 끝 validation만 켜기
val_loss_epoch_end: true
val_loss_epoch_max_batches: 30 # 똑같은수로 일단 보자고.

val_loss_alpha_mode: current
val_loss_restore_rng: true
val_loss_amp: true
#### 수정부분 끝 ####
###

# batch 작아지면 init lr도 작아지고, 웜업 스텝을 늘려야한다

image_size: 224
# batch_size: 75 # 최초
batch_size: 48 # 0.64배, 16의 배수

queue_size: 57600
alpha: 0.4

# optimizer
weight_decay: 0.05 # 유지
# init_lr: 3e-4 # 배치 75
init_lr: 1.92e-4 # 0.64 배

# min_lr: 1.0e-6 최초
min_lr: 0.64e-6 # 0.64배
# warmup_lr: 1.0e-6 # 최초
warmup_lr: 0.64e-6 # 0.64배
lr_decay_rate: 0.9
max_epoch: 20 # 테스트용. 원래 얼마더라? 20임
# warmup_steps: 3000 # 배치 75 
warmup_steps: 4700 # 배치 64



