ann_root: /home/minwoo/Distillation_Project/datasets/vision/coco/annotations/
batch_size: 16
coco_gt_root: /home/minwoo/Distillation_Project/datasets/vision/coco/annotation/coco_gt
image_root: /home/minwoo/Distillation_Project/datasets/vision/coco/images/
image_size: 224
init_lr: 1.0e-05
max_epoch: 1
max_length: 20
min_length: 5
min_lr: 0
my_bert_size: minilm
num_beams: 3
output_dir: output/caption_zeroshot/itc_lm_ep19
pretrained: /home/minwoo/Distillation_Project/output/pt_smallreg_minilm_ttm_queue_lm/checkpoint_19.pth
prompt: ''
use_spice: false
vit: small_reg
vit_ckpt_layer: 0
vit_grad_ckpt: false
weight_decay: 0.05
